version: '3.9'

services:
  stock.postgres:
    container_name: stock_postgres
    networks:
      - stock_net
    image: postgres:14.1-alpine3.14
    # volumes:
    #   - ./_cache/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 'passwd'
      POSTGRES_USER: postgres
      POSTGRES_DB: 'jobsity_stock'
      PGDATA: '/var/lib/postgresql/data'
    ports:
      - 5432:5432

  stock.service:
    container_name: stock_service
    networks:
      - stock_net
    build:
      context: .
      dockerfile: ./docker/service/Dockerfile.dev
    volumes:
      - .:/app
      - /app/node_modules/
    ports:
      - 3000:3000
    # platform: "linux/amd64"

networks:
  stock_net:
    name: stock_net
