export { default as auth } from './auth'
export { default as register } from './register'
export { default as home } from './home'
export { default as stock } from './stock'
export { default as history } from './history'
export { default as stats } from './stats'
